### ISSUE TITLE
it seems that your test code is too simple ，but what  should  be imported？

### ISSUE THREAD

**Issue by StevenLzq** [gmum/HyperNeRFGAN#7]
with pickle_path.open('rb') as f:
  content = pickle.load(f)

G = content['G_ema'].eval()

torch.manual_seed(0)
z = torch.randn(batch_size, 128)
imgs = G(z=z, c=None, scale=False, crop=False, perturb=False)

**Comment by remilvus** [comment]
Hi, sorry before I only had time to provide a minimal example. I've just added a script to generate the images. Additionally, it also visualizes interpolation between latent codes.

When time allows, I'll also add mesh/video generation. Let me know if there are any other problems.

**Comment by StevenLzq** [comment]
Thank you very much for your contribution. It is a meaningful endeavor for us
